// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMFDkKlyvr6zvzaW2kx2oQ8090ABwFdYs',
    appId: '1:519909098010:web:44b8da8a00dae23a8647a3',
    messagingSenderId: '519909098010',
    projectId: 'lexpedition-9c482',
    authDomain: 'lexpedition-9c482.firebaseapp.com',
    databaseURL: 'https://lexpedition-9c482-default-rtdb.firebaseio.com',
    storageBucket: 'lexpedition-9c482.appspot.com',
    measurementId: 'G-FJL2C3K7GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtaJQitbLYrNyDbKbQQPWoVAFO1WNBmhE',
    appId: '1:519909098010:android:4b7f467f802d5c088647a3',
    messagingSenderId: '519909098010',
    projectId: 'lexpedition-9c482',
    databaseURL: 'https://lexpedition-9c482-default-rtdb.firebaseio.com',
    storageBucket: 'lexpedition-9c482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBkb1TkOy3GTE2Eubf2ehHfqs8ad6qnK0',
    appId: '1:519909098010:ios:b8907eb4262548dd8647a3',
    messagingSenderId: '519909098010',
    projectId: 'lexpedition-9c482',
    databaseURL: 'https://lexpedition-9c482-default-rtdb.firebaseio.com',
    storageBucket: 'lexpedition-9c482.appspot.com',
    androidClientId: '519909098010-qgiop3d1egvp2h7asc85ir0ock2n8bp2.apps.googleusercontent.com',
    iosClientId: '519909098010-qb67kjpgonk2rdvrdf7odl872ha7vulc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBkb1TkOy3GTE2Eubf2ehHfqs8ad6qnK0',
    appId: '1:519909098010:ios:cebe3655563819d58647a3',
    messagingSenderId: '519909098010',
    projectId: 'lexpedition-9c482',
    databaseURL: 'https://lexpedition-9c482-default-rtdb.firebaseio.com',
    storageBucket: 'lexpedition-9c482.appspot.com',
    androidClientId: '519909098010-qgiop3d1egvp2h7asc85ir0ock2n8bp2.apps.googleusercontent.com',
    iosClientId: '519909098010-2dmj6t7shoomv4hda07bbb0mbvr9m9ip.apps.googleusercontent.com',
    iosBundleId: 'games.kinship.lexpedition',
  );
}
