import 'package:lexpedition/src/game_data/game_level.dart';
import 'package:lexpedition/src/tutorial/tutorial_window.dart';

// Copyright 2022, the Flutter project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

var tutorialLevels = [
  GameLevel(name: "The Game Board", averageGuesses: 1, bestAttempt: 1, tutorialNumber: 1, gridCode: [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    't010',
    'c010',
    null,
    null,
    null,
    null,
    'a010',
    'o010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ],
  tutorialSteps: [
    [TutorialWindow(windowType: TutorialWindowType.gameBoard), TutorialWindow(windowType: TutorialWindowType.text, text: "The game board is a 6x4 grid which can hold up to 24 letter tiles", position: TutorialTextPosition.topLeft, ignorePointer: false)],
    [TutorialWindow(windowType: TutorialWindowType.infoPanel), TutorialWindow(windowType: TutorialWindowType.text, text: "The top of the board has several items that we will learn about as you progress through the tutorials", position: TutorialTextPosition.middleLeft, ignorePointer: false)],
    [TutorialWindow(windowType: TutorialWindowType.letterGrid), TutorialWindow(windowType: TutorialWindowType.text, text: "The grid is where you create words by selecting letter tiles", position: TutorialTextPosition.topLeft, ignorePointer: false)],
    [TutorialWindow(windowType: TutorialWindowType.tile, tileIndex: 9), TutorialWindow(windowType: TutorialWindowType.text, text: "Tap on a tile to select it", position: TutorialTextPosition.topMiddle)],
    [TutorialWindow(windowType: TutorialWindowType.answerBox), TutorialWindow(windowType: TutorialWindowType.text, text: "The answer box shows your current guess", position: TutorialTextPosition.middle, ignorePointer: false)],
    [TutorialWindow(windowType: TutorialWindowType.tile, tileIndex: 15), TutorialWindow(windowType: TutorialWindowType.answerBox), TutorialWindow(windowType: TutorialWindowType.text, text: "Now select the letter tile with the \"O\"", position: TutorialTextPosition.bottomMiddle)],
    [TutorialWindow(windowType: TutorialWindowType.tile, tileIndex: 14), TutorialWindow(windowType: TutorialWindowType.answerBox), TutorialWindow(windowType: TutorialWindowType.text, text: "Next select the letter tile with the \"A\"", position: TutorialTextPosition.bottomMiddle)],
    [TutorialWindow(windowType: TutorialWindowType.tile, tileIndex: 8), TutorialWindow(windowType: TutorialWindowType.answerBox), TutorialWindow(windowType: TutorialWindowType.text, text: "Finally, select the letter tile with the \"T\"", position: TutorialTextPosition.bottomMiddle)],
    [TutorialWindow(windowType: TutorialWindowType.submit), TutorialWindow(windowType: TutorialWindowType.answerBox), TutorialWindow(windowType: TutorialWindowType.text, text: 'Tap the submit button to submit your current guess', position: TutorialTextPosition.middle, ignorePointer: false)],
  ]
  ),
  GameLevel(name: "Multiple Charges", averageGuesses: 3, bestAttempt: 3, tutorialNumber: 2, gridCode: [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'b020',
    'r020',
    null,
    null,
    null,
    null,
    'a030',
    'e010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ]),
  GameLevel(name: "Start Tile", averageGuesses: 3, bestAttempt: 2, tutorialNumber: 3, gridCode: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      't020',
      'e110',
      null,
      null,
      null,
      null,
      'a020',
      'm110',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
  ),
  GameLevel(name: "End Tile", averageGuesses: 3, bestAttempt: 2, tutorialNumber: 4, gridCode: [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'e210',
    't210',
    null,
    null,
    null,
    null,
    'a020',
    'r010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ]),
  GameLevel(name: "All 3 Tile Types", averageGuesses: 5, bestAttempt: 3, tutorialNumber: 5, gridCode: [
    null,
    'e210',
    't220',
    's010',
    null,
    null,
    null,
    'a020',
    'r110',
    'o020',
    null,
    null,
    null,
    'l010',
    'p120',
    'd010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ]),
  GameLevel(name: "Magic Blast", averageGuesses: 2, bestAttempt: 2, tutorialNumber: 6, gridCode: [
    't110',
    'r010',
    'e010',
    null,
    'x010',
    null,
    null,
    'a010',
    't010',
    null,
    null,
    'x010',
    null,
    null,
    null,
    null,
    null,
    null,
    'b110',
    'e010',
    'a010',
    's010',
    't210',
    null
  ]),
  GameLevel(name: "Obstacles", averageGuesses: 2, bestAttempt: 2, tutorialNumber: 7, gridCode: [
    null,
    null,
    null,
    null,
    'j111',
    null,
    null,
    null,
    null,
    null,
    'o011',
    null,
    null,
    null,
    null,
    null,
    'b211',
    null,
    'g110',
    'r010',
    'e010',
    'a010',
    't220',
    null
  ])
];

