import 'package:game_template/src/game_data/levels.dart';

import '../game_data/letter_grid.dart';

// Copyright 2022, the Flutter project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

var tutorialLevels = [
  TutorialLevel(name: 'Basic Tile', number: 1, difficulty: 2, gridCode: [
    't020',
    'c020',
    null,
    null,
    null,
    null,
    'a020',
    'o010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ]),
  TutorialLevel(
    name: 'Start Tile',
    number: 2,
    difficulty: 2,
    gridCode: [
      't020',
      'e110',
      null,
      null,
      null,
      null,
      'a020',
      'm110',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
  ),
  TutorialLevel(name: 'End Tile', number: 3, difficulty: 2, gridCode: [
    'e210',
    't210',
    null,
    null,
    null,
    null,
    'a020',
    'r010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ]),
  TutorialLevel(name: 'All 3 Tile Types', number: 4, difficulty: 4, gridCode: [
    'e220',
    't210',
    's010',
    null,
    null,
    null,
    'a030',
    'r110',
    'o010',
    null,
    null,
    null,
    'l020',
    'p110',
    'd010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ]),
  TutorialLevel(name: 'Magic Blast', number: 5, difficulty: 4, gridCode: [
    'e210',
    't010',
    's010',
    'z010',
    null,
    null,
    'a030',
    'r120',
    'r010',
    'n010',
    null,
    null,
    'l020',
    'p010',
    'd010',
    'u010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ]),
  TutorialLevel(name: 'Obstacles', number: 6, difficulty: 5, gridCode: [
    'e210',
    't010',
    's011',
    'z010',
    null,
    null,
    'a030',
    'r121',
    'r010',
    'n010',
    null,
    null,
    'l020',
    'p010',
    'd010',
    'u010',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ])
];
